### ISSUE TITLE
Roadmap of deployment

### ISSUE THREAD

**Issue by heliqi** [PaddlePaddle/PaddleX#762]
#v2.1   计划2021.08
- [x] python部署 
- [ ] 支持PaddleLite
- [ ] 部署性能Benchmark
- [ ] Triton原生与基于ONNX的对比情况
- [ ] PaddleServing or Triton 服务化部署
- [ ] 预处理再加速 

# v2.0.0 rc3 计划2021.07
- [x] PaddleInference在jetson编译部署 (受限于引擎和opencv，推到下期上)
- [x] 文档完善优化(编译文档、编译dll文档、C#、使用dll文档)
- [x] 测试库中PaddleDetection、PaddleClas、PaddleSeg测试流程改为git clone代码后重新导出模型进行测试
- [x] 代码优化
- [x] 模型加密的使用方式修改

# v2.0.0rc2 计划2021.06
- [x] ONNX部署、READEME等文档更新
- [x] PaddleInference集成TensorRT 
- [x] 预处理加速
- [x] 2.0支持OpenVINO
- [x] cpp加密部署
- [x] 代码关键函数及字段的注释
- [x] 编译打包SDK

# v2.0.0rc0 计划2021.05
- [x] 支持PaddleX、PaddleDetection、PaddleSeg、PaddleClas多套件部署
- [x] 部署文档
- [x] MaskRCNN支持
- [x] 基于TensorRT部署ONNX模型(已支持分类clas、分割seg模型)
- [x] Triton服务化部署ONNX模型(已支持分类clas、分割seg模型)
- [x]  多卡部署
- [x] 代码结构优化

**Comment by jiangjiajun** [comment]
# PaddleX 2.0部署模块
- 适配PaddleInference 2.0预测库
- 支持PaddleSeg、PaddleDetection、PaddleClas模型的部署
- 支持PaddleX模型部署
代码路径： https://github.com/PaddlePaddle/PaddleX/tree/develop/dygraph/deploy/cpp

**Comment by jiangjiajun** [comment]
代码缺少注释信息，例如在PaddleSeg中的后处理Run()和RunV2两个函数（这个PR https://github.com/PaddlePaddle/PaddleX/pull/790 ）分别是用于做什么的，在下个版本中需完善这些注释信息 @heliqi
